### ISSUE TITLE
停止支持win7是指后续版本不再支持还是全版本？

### ISSUE THREAD

**Issue by xushet** [Rinacm/Pixeval#102]
rt，

**Comment by Rinacm** [comment]
后续版本，好处是体积也许会大大减小，登录也会更加稳定

**Comment by xushet** [comment]
> 后续版本，好处是体积也许会大大减小，登录也会更加稳定

是因为自带运行库的问题么？

**Comment by Rinacm** [comment]
不是，是因为在win7上想要实现webapi免代理必须内置一个CefSharp(200多M，最初没有cefsharp的版本一共才20多M)，另外想要写自定义协议唤起必须要自己写一个bridge(源码中的Pixeval.Interchange)，而win10自带了自定义协议的API

**Comment by xushet** [comment]
知晓
