### ISSUE TITLE
一大堆bug

### ISSUE THREAD

**Issue by Cyl18** [Rinacm/Pixeval#15]
看链接
https://youtu.be/l0CUkCMBXGU
问题包括：

- [x] 在窗口很小的情况下左侧导航栏无法完全显示（可以添加滚动条）
- [x] 在窗口很小的情况下点开图片详情无法退出（包括esc键都不行）
- [x] 日推很容易出现重复图片 之前测试甚至遇到了8张重复
- [ ] 有的时候会莫名其妙出现白图（可能是上面那条的关系）
- [ ] 点开之后列表会一直刷新
- [ ] 点开一张图要点很多次
- [ ] 用户新作那个icon和其他icon明显不一样
- [x] 小按钮需要tooltip来提示作用

建议：

- [x] 模糊效果会让图片朝着右下角移动 不知道是design还是咋地
- [ ] 添加瀑布预览图效果（就是跟着图片的大小缩放的container而不是固定的）

**Comment by Rinacm** [comment]
关于第4条: 出现白图是网络问题，可以尝试重新点击缩略图
关于第5条: 一直刷新是刻意为之，因为我测试之后感觉缓存系统得不偿失
关于第6条: 这是Material Design DialogHost的问题，我之前尝试解决过但是失败了，原因看我1月22日的commit: https://github.com/Rinacm/Pixeval/commit/0cd8c0971aa635c1973b89f2995a3113811179da#diff-dae1ae44d70a47d7339d20909aa164f9R182 如果去掉这里的e.Handle = true，那么在浏览用户界面时点击缩略图会导致ScrollBar直接回滚到最上方(我也不知道为什么), 我所能想到的唯一办法就是用e.Handled = true阻断事件传播，但是这样的话会导致点击缩略图时有概率无法显示大图，解决方法是左键单击的时间稍微长一些。
关于第10条：使用瀑布流视图就没有办法进行虚拟化了，对于一次最多需要load3000张图片的控件来说不用虚拟化的代价太大了
