### ISSUE TITLE
建议加入 私人关注，私人收藏夹 和 搜索历史 功能

### ISSUE THREAD

**Issue by TheresaQWQ** [Rinacm/Pixeval#16]

**Comment by Rinacm** [comment]
会尽快处理，现在在着手写标签趋势，以图搜图和部分ui的美化

**Comment by TheRealKamisama** [comment]
私人收藏我好像在你之前beta的时候我自己写了一个(

**Comment by Rinacm** [comment]
> 私人收藏我好像在你之前beta的时候我自己写了一个(

rwkk

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/releases/tag/1.9.0
