### ISSUE TITLE
建议在*设置*里面加一个*代理服务器设置*

### ISSUE THREAD

**Issue by Veronicarin-Yuukinan** [Rinacm/Pixeval#17]
因为想用自己的代理服务器，这样速度会快一些，虽然我可以用SocksCap单独给软件走代理通道，但还是希望能内置这个功能

**Comment by Veronicarin-Yuukinan** [comment]
单独用SocksCap给软件走代理不行，刚试验过了，不走数据

**Comment by Yurzi** [comment]
我也觉得可以在设置里 加一个代理服务器设置

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/commit/5907b1e14ab6dd2633ecf7c30d58cdfe6695aa4a

**Comment by Rinacm** [comment]
fixed https://github.com/Rinacm/Pixeval/commit/5d46cc4adb17c7022cf697256b11defc920b145f
