### ISSUE TITLE
反馈一个关于图片加载的问题

### ISSUE THREAD

**Issue by Veronicarin-Yuukinan** [Rinacm/Pixeval#18]
比如说我进入*我的收藏*，页面右边会加载出所有图片，但是我把页面向下滚动之后再滚动回去，之前加载的图片会需要再次加载，另外我在滚动页面的时候会出现粘滞感，感觉不是很流畅

**Comment by Rinacm** [comment]
之前加载图片再次加载是因为虚拟化，这样做节省了内存占用，不在viewport的控件都会被unload，滚动页面的粘滞感是因为wpf的滚动条只能设定一次滚动多少像素，不能完全的平滑滚动

**Comment by Veronicarin-Yuukinan** [comment]
我寻思要不整一个高性能按钮？有些老铁估计也不差内存

**Comment by Rinacm** [comment]
那样就事半功倍了，我会考虑写一个缓存

**Comment by Rinacm** [comment]
那样就事倍功半了，我会考虑写一个缓存系统
