### ISSUE TITLE
窗口分辨率超过显示器极限

### ISSUE THREAD

**Issue by Jack6811** [Rinacm/Pixeval#19]
在使用时该程序的默认分辨率以超出我电脑的分辨率（1920x1080）,人工缩放会导致窗口显示不完整，希望作者改改代码，不在强制分辨率，采用自动兼容。

**Comment by Rinacm** [comment]
我设置的默认分辨率是1600*900，1080p应该没有任何问题，，，你可以下载一下最新版本，里面对于低分辨率做了兼容，加了几个滚动条
