### ISSUE TITLE
Linux支持的可能性？

### ISSUE THREAD

**Issue by NichtsVonChaos** [Rinacm/Pixeval#20]
既然是.NET Core开发的话，未来是否存在支持Linux的可能性？

**Comment by Rinacm** [comment]
本项目基于WPF(Windows Presentation Foundation)，WPF很多地方用了Win32 API，所以依靠本项目结构移植linux是不可能的

**Comment by q779433467** [comment]
# 那么移植到wine呢？
（诸如Deepin-wine等修改版本）

**Comment by Rinacm** [comment]
> # 那么移植到wine呢？
> （诸如Deepin-wine等修改版本）

也许可以，但是我暂时没有linux开发经验=x=
