### ISSUE TITLE
复制功能不工作

### ISSUE THREAD

**Issue by scythk** [Rinacm/Pixeval#23]
1. 点击作品后右键复制后 粘贴出来的还是之前复制的东西 偶尔能粘贴成功但找不出规律
还出现了复制之后粘贴出之前复制失败的图片的情况
2. 我的任务栏设置了自动隐藏 点击作品弹出的窗口后再下移鼠标 弹出的任务栏会被作品的窗口遮住无法点击
3. 点击作品弹出的窗口的右下方下载分享那一排按钮有时会消失
System: Win 10 1909

**Comment by Rinacm** [comment]
点击复制速度慢是因为复制是下载的原图，所以如果是分辨率高的图片会由于网速造成一定的延迟
作品窗口可以通过点击ESC键关闭
分享按钮消失的bug我会尽快处理
