### ISSUE TITLE
第一次可以正常打开exe，之后重启就不行了，双击和管理员权限都打不开

### ISSUE THREAD

**Issue by ProJeKTRED** [Rinacm/Pixeval#25]

**Comment by Rinacm** [comment]
AppData/Local/pixeval下面的crash-reports文件夹打包传上来

**Comment by 2424479089** [comment]
> AppData/Local/pixeval下面的crash-reports文件夹打包传上来

[crash-reports.zip](https://github.com/Rinacm/Pixeval/files/4248088/crash-reports.zip)

**Comment by wukefenggao-zj** [comment]
![L6LC(T%IO5P31{IFBLI1233](https://user-images.githubusercontent.com/59675430/75404648-27e31e00-5946-11ea-8814-04a29ebf9702.png)
![FGXJP~0THSIO)FGOPJE`{6O](https://user-images.githubusercontent.com/59675430/75404650-2a457800-5946-11ea-9144-2ef9dae485ca.png)

**Comment by wukefenggao-zj** [comment]
大佬，我的程序一直崩溃

**Comment by wukefenggao-zj** [comment]
问题事件名称:	APPCRASH
  应用程序名:	Pixeval.exe
  应用程序版本:	1.0.0.0
  应用程序时间戳:	5de8341a
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.23864
  故障模块时间戳:	595fa988
  异常代码:	e0434352
  异常偏移:	000000000001a06d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	c95e
  其他信息 2:	c95e0a860efbf5a6a890a228eff18769
  其他信息 3:	f2eb
  其他信息 4:	f2eb44ae82a079f0aab018a1d9fe5a3d

**Comment by wukefenggao-zj** [comment]
谢谢了

**Comment by YueGAMI** [comment]
多次使用后无法正常打开了，同样是双击和管理员权限都打不开
[crash-reports.zip](https://github.com/Rinacm/Pixeval/files/4290830/crash-reports.zip)

**Comment by qingciqiange** [comment]
同样的问题，根本无法打开。我以为是AppData/Local/pixeval文件夹的问题，直接删了，现在也没有对crash-reports文件夹了，怎么办。

**Comment by Waysidecaren** [comment]
同样的问题，不过发现是在用火绒清理垃圾时软件将AppData\Local\Temp\.net\Pixeval中文件夹内的部分文件清理掉了导致无反应

**Comment by qingciqiange** [comment]
> 同样的问题，不过发现是在用火绒清理垃圾时软件将AppData\Local\Temp.net\Pixeval中文件夹内的部分文件清理掉了导致无反应

请问找到解决方法了吗？

**Comment by Waysidecaren** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qingciqiange"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 中午11:07
收件人:&nbsp;"Rinacm/Pixeval"<Pixeval@noreply.github.com&gt;;
抄送:&nbsp;"Ω"<1493451607@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Rinacm/Pixeval] 第一次可以正常打开exe，之后重启就不行了，双击和管理员权限都打不开 (#25)





  
同样的问题，不过发现是在用火绒清理垃圾时软件将AppData\Local\Temp.net\Pixeval中文件夹内的部分文件清理掉了导致无反应
  
请问找到解决方法了吗？

**Comment by Waysidecaren** [comment]
> > 同样的问题，不过发现是在用火绒清理垃圾时软件将AppData\Local\Temp\.net\Pixeval中文件夹内的部分文件清理掉了导致无反应
> 
> 请问找到解决方法了吗？

AppData\Local\Temp\.net\Pixeval 可以将这个路径的文件删除，然后重新打开Pixeval，会能成功启动并重新生成完整的文件内容，但是再次清理时还是会出现文件被删除的情况

**Comment by Rinacm** [comment]
已修复
