### ISSUE TITLE
浏览图片窗口无法滑动

### ISSUE THREAD

**Issue by Vixbob** [Rinacm/Pixeval#27]
![QQ图片20200225172716](https://user-images.githubusercontent.com/30905336/75234241-353cc300-57f5-11ea-947b-d6b096f78a19.png)

如图，图片没有显示完整，并且无法滑动。

**Comment by Rinacm** [comment]
这个bug有人反馈过，已经在更新了

**Comment by Vixbob** [comment]
> 这个bug有人反馈过，已经在更新了

哦，我看您没回复直接close掉了，还以为您直接忽略他了（-_-||）

**Comment by Rinacm** [comment]
> > 这个bug有人反馈过，已经在更新了
> 
> 哦，我看您没回复直接close掉了，还以为您直接忽略他了（-_-||）

主要是最近一直在摸鱼.....

**Comment by Vixbob** [comment]
> > > 这个bug有人反馈过，已经在更新了
> > 
> > 
> > 哦，我看您没回复直接close掉了，还以为您直接忽略他了（-_-||）
> 
> 主要是最近一直在摸鱼.....

摸鱼可还行

**Comment by Rinacm** [comment]
已修复 https://github.com/Rinacm/Pixeval/commit/5d46cc4adb17c7022cf697256b11defc920b145f
