### ISSUE TITLE
在每日推荐中下载多图作品容易出现空文件夹

### ISSUE THREAD

**Issue by Rigil-Kentaurus** [Rinacm/Pixeval#28]
如题，在每日推荐中下载多图作品容易出现空文件夹，无论是直接点击下载还是添加到下载列表再按下载，等待较长时间、挂代理后依然如此。测试版本为1.3.0，1.0.2挂代理后似乎无此现象，应该能排除网络因素。
复制ID在客户端中搜索后下载出现该问题概率极大减小。

另：希望对无论是直接点击下载还是添加到下载列表再按下载都有个进度条或者进度汇总，以及明确的挂/不挂代理设置。

挂代理方式为SSR客户端的全局代理模式，应该是改IE（系统）的代理设置。

**Comment by Rinacm** [comment]
fixed https://github.com/Rinacm/Pixeval/commit/5d46cc4adb17c7022cf697256b11defc920b145f
