### ISSUE TITLE
我没有用过这个 第三方控件 密码无法输入，UI卡死!!

### ISSUE THREAD

**Issue by handashuai** [Rinacm/Pixeval#29]
还有 好多网络 接口 返回null 没有做判断  ，导致代码 全是崩溃的

**Comment by Rinacm** [comment]
我怀疑你是用Debug跑的，因为我的null处理一律用Release屏蔽掉

**Comment by Rinacm** [comment]
另外UI无法输入根本就不是第三方控件的问题，是WPF的passwordbox本身就没法用IME，你要是写过WPF应该清楚这点

**Comment by handashuai** [comment]
> passwordbox

passwordbox 原生wpf 可以输入 不知道这个三方控件 啥原因
