### ISSUE TITLE
你的软件被人拿去公众号引流了

### ISSUE THREAD

**Issue by xushet** [Rinacm/Pixeval#32]

**Comment by Rinacm** [comment]
？？？？？what

**Comment by xushet** [comment]
小学安日常操作https://www.coolapk.com/feed/16706721
[截图``](<a href="https://sm.ms/image/APMdBGq5nkZRODE" target="_blank"><img src="https://i.loli.net/2020/03/13/APMdBGq5nkZRODE.jpg" ></a>)

**Comment by xushet** [comment]
我看着挺难受的，不知道你怎么想

**Comment by Rinacm** [comment]
其实我管不了....虽然我也不喜欢别人拿我写的东西去引流，但是这种我也没办法...
就算我上去声明....我觉得也起不到多大作用，换个角度想，反正都是开源软件，他宣传出去说不定能帮到更多人，也就懒得管太多了

**Comment by Yurzi** [comment]
作者大大，你可以加入一个“关于”的界面，其中可以声明版本信息，源代码作者，开源协议等，这样至少好点

**Comment by Rinacm** [comment]
> 作者大大，你可以加入一个“关于”的界面，其中可以声明版本信息，源代码作者，开源协议等，这样至少好点

刚刚朋友也给我提到了233，我下午会加上的

**Comment by NotFoundNEKKO** [comment]
我觉得这些自己开发的东西就算是开源也要声明，毕竟这些自己的东西如果直接给别人拿去用说实话我觉得接受不了
