### ISSUE TITLE
希望添加图片放大或者全屏的功能

### ISSUE THREAD

**Issue by wbygit** [Rinacm/Pixeval#33]
图片展示的窗口比较小，要是能吧图片全屏或者放大就好了。

**Comment by Rinacm** [comment]
没有写全屏是有意为之(，另外考虑到用户体验所以实际上图片浏览时候显示的并不是原图，如果是原图的话加载速度会比较看脸，所以图片浏览的作用仅仅是让用户对该图片有个大概的印象，想要仔细欣赏可以点击下载按钮下载(
