### ISSUE TITLE
大神Pixeval不能运行

### ISSUE THREAD

**Issue by zz8484321** [Rinacm/Pixeval#35]
已经点击压缩包的链接下载并安装.NET Core v3.1，但是不能运行Pixeval是什么原因啊是NET Core必须要下载3.0版本的么好，还是下载完NET Core v3.1还要在文件夹里点击某个文件在运行Pixeval啊我是电脑白痴

**Comment by Rinacm** [comment]
系统版本是什么

**Comment by zz8484321** [comment]
> 系统版本是什么

是盗版的WIN7 64系统
![360截图20200313120108865](https://user-images.githubusercontent.com/62127385/76588675-88678300-6522-11ea-988f-b1a10788818a.jpg)

**Comment by zz8484321** [comment]
> 系统版本是什么

然后我又把那什么NET3.0的什么X86的全安装了也不能运行
![360截图20200313120422972](https://user-images.githubusercontent.com/62127385/76588746-c95f9780-6522-11ea-828a-f07b776162e3.jpg)

**Comment by Rinacm** [comment]
打开windows事件查看器，看下日志里面有Pixeval相关的提示什么

**Comment by zz8484321** [comment]
已经用网站的issue恢复大神，
----- 原始邮件 -----
发件人：Dylech30th <notifications@github.com>
收件人：Rinacm/Pixeval <Pixeval@noreply.github.com>
抄送人：zz8484321 <qq8484321@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[Rinacm/Pixeval]_大神Pixeval不能运行_(#35)
日期：2020年03月13日 11点59分



系统版本是什么



&mdash;

**Comment by zz8484321** [comment]
> ：windows事件查看器，看里面的里面有Pixeval相关的提示什么

![360截图20200313121157761](https://user-images.githubusercontent.com/62127385/76589097-e3e64080-6523-11ea-9ab6-c2fadb71b7fc.jpg)
是这个么大神

**Comment by Rinacm** [comment]
> > ：windows事件查看器，看里面的里面有Pixeval相关的提示什么
> 
> ![360截图20200313121157761](https://user-images.githubusercontent.com/62127385/76589097-e3e64080-6523-11ea-9ab6-c2fadb71b7fc.jpg)
> 是这个么大神

是的，点开让我看看详细信息

**Comment by zz8484321** [comment]
> ：windows事件查看器，看里面的里面有Pixeval相关的提示什么

大神这个是哪个错误的友好视图内容

- | System
-- | --





> > > ：windows事件查看器，看里面的里面有Pixeval相关的提示什么
> > 
> > 
> > ![360截图20200313121157761](https://user-images.githubusercontent.com/62127385/76589097-e3e64080-6523-11ea-9ab6-c2fadb71b7fc.jpg)
> > 是这个么大神
> 
> 是的，点开让我看看详细信息

详细信息XML视图
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1023</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-13T04:11:17.000000000Z" /> 
  <EventRecordID>25575</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-20120726XSHJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Description: A .NET Core application failed. Application: Pixeval.exe Path: D:\Pixeval\Pixeval.exe Message: Error: An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found: package: 'PropertyChanged.Fody', version: '3.2.1' path: 'lib/netstandard1.0/PropertyChanged.dll'</Data> 
  </EventData>
  </Event>

**Comment by zz8484321** [comment]
> > ：windows事件查看器，看里面的里面有Pixeval相关的提示什么
> 
> 大神这个是该错误的友好查看内容
> 
> * | 系统
>   -| -
> 
> > > > ：windows事件查看器，看里面的里面有Pixeval相关的提示什么
> > > 
> > > 
> > > ![360截图20200313121157761](https://user-images.githubusercontent.com/62127385/76589097-e3e64080-6523-11ea-9ab6-c2fadb71b7fc.jpg)
> > > 是这个么大神
> > 
> > 
> > 是的，点开让我看看详细信息
> 
> 详细信息XML视图
> 
> * 
> * 1023 2 0 0x80000000000000 25575应用程序PC-20120726XSHJ
> * 说明：.NET Core应用程序失败。应用程序：Pixeval.exe路径：D：\ Pixeval \ Pixeval.exe消息：错误：找不到在应用程序依赖项清单（Pixeval.deps.json）中指定的程序集：包：'PropertyChanged.Fody'，版本：'3.2 .1'路径：'lib / netstandard1.0 / PropertyChanged.dll'

友好视图

Description: A .NET Core application failed. Application: Pixeval.exe Path:  D:\Pixeval\Pixeval.exe Message: Error: An assembly specified in the application  dependencies manifest (Pixeval.deps.json) was not found: package:  'PropertyChanged.Fody', version: '3.2.1' path:  'lib/netstandard1.0/PropertyChanged.dll'
--

**Comment by zz8484321** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1023</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-13T04:11:17.000000000Z" /> 
  <EventRecordID>25575</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-20120726XSHJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Description: A .NET Core application failed. Application: Pixeval.exe Path: D:\Pixeval\Pixeval.exe Message: Error: An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found: package: 'PropertyChanged.Fody', version: '3.2.1' path: 'lib/netstandard1.0/PropertyChanged.dll'</Data> 
  </EventData>
  </Event>

**Comment by zz8484321** [comment]
日志名称:          Application
来源:            .NET Runtime
日期:            2020/3/13 12:11:17
事件 ID:         1023
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC-20120726XSHJ
描述:
Description: A .NET Core application failed.
Application: Pixeval.exe
Path: D:\Pixeval\Pixeval.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found:
    package: 'PropertyChanged.Fody', version: '3.2.1'
    path: 'lib/netstandard1.0/PropertyChanged.dll'


事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-13T04:11:17.000000000Z" />
    <EventRecordID>25575</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20120726XSHJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Description: A .NET Core application failed.
Application: Pixeval.exe
Path: D:\Pixeval\Pixeval.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found:
    package: 'PropertyChanged.Fody', version: '3.2.1'
    path: 'lib/netstandard1.0/PropertyChanged.dll'

</Data>
  </EventData>
</Event>

**Comment by zz8484321** [comment]
日志名称:          Application
来源:            .NET Runtime
日期:            2020/3/13 12:11:17
事件 ID:         1023
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC-20120726XSHJ
描述:
Description: A .NET Core application failed.
Application: Pixeval.exe
Path: D:\Pixeval\Pixeval.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found:
    package: 'PropertyChanged.Fody', version: '3.2.1'
    path: 'lib/netstandard1.0/PropertyChanged.dll'


事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-13T04:11:17.000000000Z" />
    <EventRecordID>25575</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC-20120726XSHJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Description: A .NET Core application failed.
Application: Pixeval.exe
Path: D:\Pixeval\Pixeval.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found:
    package: 'PropertyChanged.Fody', version: '3.2.1'
    path: 'lib/netstandard1.0/PropertyChanged.dll'

</Data>
  </EventData>
</Event>
----- 原始邮件 -----
发件人：Dylech30th <notifications@github.com>
收件人：Rinacm/Pixeval <Pixeval@noreply.github.com>
抄送人：zz8484321 <qq8484321@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[Rinacm/Pixeval]_大神Pixeval不能运行_(#35)
日期：2020年03月13日 12点13分







：windows事件查看器，看里面的里面有Pixeval相关的提示什么






是这个么大神



是的，点开让我看看详细信息



&mdash;

**Comment by kami-poi** [comment]
> 日志名称: Application 来源: .NET Runtime 日期: 2020/3/13 12:11:17 事件 ID: 1023 任务类别: 无 级别: 错误 关键字: 经典 用户: 暂缺 计算机: PC-20120726XSHJ 描述: Description: A .NET Core application failed. Application: Pixeval.exe Path: D:\Pixeval\Pixeval.exe Message: Error: An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found: package: 'PropertyChanged.Fody', version: '3.2.1' path: 'lib/netstandard1.0/PropertyChanged.dll' 事件 Xml: <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> <System> <Provider Name=".NET Runtime" /> <EventID Qualifiers="0">1023</EventID> <Level>2</Level> <Task>0</Task> <Keywords>0x80000000000000</Keywords> <TimeCreated SystemTime="2020-03-13T04:11:17.000000000Z" /> <EventRecordID>25575</EventRecordID> <Channel>Application</Channel> <Computer>PC-20120726XSHJ</Computer> <Security /> </System> <EventData> <Data>Description: A .NET Core application failed. Application: Pixeval.exe Path: D:\Pixeval\Pixeval.exe Message: Error: An assembly specified in the application dependencies manifest (Pixeval.deps.json) was not found: package: 'PropertyChanged.Fody', version: '3.2.1' path: 'lib/netstandard1.0/PropertyChanged.dll' </Data> </EventData> </Event> ----- 原始邮件 ----- 发件人：Dylech30th <notifications@github.com> 收件人：Rinacm/Pixeval <Pixeval@noreply.github.com> 抄送人：zz8484321 <qq8484321@sina.com>, Comment <comment@noreply.github.com> 主题：Re:_[Rinacm/Pixeval]_大神Pixeval不能运行_(#35) 日期：2020年03月13日 12点13分 ：windows事件查看器，看里面的里面有Pixeval相关的提示什么 是这个么大神 是的，点开让我看看详细信息 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没有查找到程序集 看一下你Pixeval根目录下有没有PropertyChanged.dll这个文件，是不是误删掉了

**Comment by zz8484321** [comment]
大神我刚才有运行了一下打开了结果Pixeval已停止工作出现了一个问题
![360截图20200313123329034](https://user-images.githubusercontent.com/62127385/76590021-fca42580-6526-11ea-9e91-db32104c7470.jpg)

**Comment by zz8484321** [comment]
刚才关了有打开一下，就上去了我也不知道是怎么回事

**Comment by Rinacm** [comment]
更新了release，下载新版本试下看有没有问题

**Comment by Rinacm** [comment]
https://github.com/dotnet/runtime/issues/8792

**Comment by zz8484321** [comment]
大神下载了
![360截图20200313124827890](https://user-images.githubusercontent.com/62127385/76590701-fdd65200-6528-11ea-916a-a890bec8102d.jpg)
然后打开了，上去就是什么都刷新不出来，是那个设置里的直连选项开与关的问题么

**Comment by Rinacm** [comment]
> 大神下载了
> ![360截图20200313124827890](https://user-images.githubusercontent.com/62127385/76590701-fdd65200-6528-11ea-916a-a890bec8102d.jpg)
> 然后打开了，上去就是什么都刷新不出来，是那个设置里的直连选项开与关的问题么

是的，直连默认是关闭的，关闭时必须要挂梯子，打开了会开启直连模式不需要挂梯子

**Comment by zz8484321** [comment]
大神打开了完全好了能用了，谢谢大神
