### ISSUE TITLE
还是笔记本的显示问题

### ISSUE THREAD

**Issue by NakataniIku** [Rinacm/Pixeval#36]
今天下载新文件夹后打开笔记本底部还是显示不出下载按钮标签等，而且不知道为啥右击图片也没有复制选项了  笔记本分辨率1366X768

**Comment by Rinacm** [comment]
复制被我删掉了，因为下载大图太慢了..至于1366x768...这个不在支持的分辨率范围内...我支持的最低分辨率是1600x900，后续可能会考虑添加低分辨率的自适应

**Comment by NakataniIku** [comment]
> 复制被我删除掉了，因为下载大图太慢了..至于1366x768 ...这个不在支持的分辨率范围内...我支持的最低分辨率是1600x900，后续可能会考虑添加低分辨率的自适应

好的
