### ISSUE TITLE
点击下载没有反应

### ISSUE THREAD

**Issue by niyuyeye** [Rinacm/Pixeval#37]
1.4.0版本，点击下载没有反应

**Comment by Rinacm** [comment]
什么叫点击下载没有反应？去下载列表看一下，你点击完下载就会自动加入到下载列表然后下载到你设置里设置的目标文件夹

**Comment by niyuyeye** [comment]
下载列表里没有显示，但是文件夹里有图片

**Comment by Rinacm** [comment]
> 下载列表里没有显示，但是文件夹里有图片

那就是下载太快了(
你没来的及打开列表就下载完了
同时多下载几个就可以在下载列表里看进度了
