### ISSUE TITLE
1.5无法打开，1.4没问题

### ISSUE THREAD

**Issue by OdinShiva** [Rinacm/Pixeval#39]
win10 专业工作站版 1909 64位

**Comment by Rinacm** [comment]
怎么个无法打开法？双击没反应？如果是这样的话win+r输入eventvwr打开查看windows日志，里面有包含.Net Core Runtime的错误详细内容发过来

**Comment by OdinShiva** [comment]
> 怎么个无法打开法？双击没反应？如果是这样的话win+r输入eventvwr打开查看windows日志，里面有包含.Net Core Runtime的错误详细内容发过来

哦 

Description: A .NET Core application failed. Application: Pixeval.exe Path:  D:\Program Files\Pixeval\Pixeval.exe Message: A fatal error occurred. The  required library hostfxr.dll could not be found. If this is a self-contained  application, that library should exist in [D:\Program Files\Pixeval\]. If this  is a framework-dependent application, install the runtime in the global location  [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify  the runtime location or register the runtime location in  [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].
--

**Comment by OdinShiva** [comment]
发现重装net core 就好了

**Comment by TheRealKamisama** [comment]
![图片](https://user-images.githubusercontent.com/35005476/76672789-5285d580-65da-11ea-9e97-e7090c72e3bb.png)

**Comment by Rinacm** [comment]
你再笑？
