### ISSUE TITLE
1.5.0中遇到的问题

### ISSUE THREAD

**Issue by wbygit** [Rinacm/Pixeval#40]
（1）组图无法翻页，只能查看第一张
（2）点击图片标签搜索的功能似乎没有了？日语苦手表示很依赖这个功能

**Comment by wbygit** [comment]
环境：

**Comment by wbygit** [comment]
系统环境：Windows10 64位 1909

**Comment by wbygit** [comment]
刚才又试了一下，标签的问题只存在于关键字搜索时，从我的收藏或者直接输入图片id里打开图片点击标签没有问题

**Comment by Rinacm** [comment]
已经在新版本修复

**Comment by wbygit** [comment]
感谢作者大大的爆肝更新！
可1.6.0我又发现一个标签的bug，在画师的插画和收藏的图片点击标签莫得反应

**Comment by Rinacm** [comment]
已修复，重启软件应该能看到更新

**Comment by wbygit** [comment]
![图像 1](https://user-images.githubusercontent.com/35754856/76694774-250c5b00-66b2-11ea-8233-391e8a2132b5.png)
见图片，自动更新报错。
但似乎确实更新到1.6.1了，我看那个bug也修复了

**Comment by wbygit** [comment]
github这附件上传似乎有点毛病，我链到我的服务器吧
[http://www.prpr.site/download/Pixeval.bug.png](更新错误截图)

**Comment by wbygit** [comment]
github这附件上传似乎有点毛病，点下面这个链接吧，是错误截图
http://www.prpr.site/download/Pixeval.bug.png

**Comment by Rinacm** [comment]
已经在release中更新，请前往release下载最新版本
