### ISSUE TITLE
无法显示收藏夹其他还没试过

### ISSUE THREAD

**Issue by NotFoundNEKKO** [Rinacm/Pixeval#42]
![TIM图片20200315223005](https://user-images.githubusercontent.com/47251157/76703428-a1cc2300-670c-11ea-8b82-4cab1b67f0c9.png)
![TIM截图20200315223028](https://user-images.githubusercontent.com/47251157/76703431-a5f84080-670c-11ea-8412-5aabed640fe8.png)

**Comment by Rinacm** [comment]
启用直连。。。。。

**Comment by Rinacm** [comment]
![image](https://user-images.githubusercontent.com/31894334/76710002-8b3ebf80-673e-11ea-8a35-be7b22102fe5.png)
