### ISSUE TITLE
设置中的起始页设置和按收藏数排序似乎是无效的

### ISSUE THREAD

**Issue by naSgnahZ** [Rinacm/Pixeval#46]
无论如何设置起始页搜索,搜索的结果都是一样的.
是否打开按收藏数排序的设置,似乎结果都是按照收藏数排序的.

**Comment by Rinacm** [comment]
起始页仅仅对于关键字搜索有效
收藏数排序仅仅对于日推和关键字搜索有效，其余的全部按照日期排序

**Comment by zccored** [comment]
那ID咋办？不会要一页一页翻吧...（建议后期修改：投稿功能、gif播放功能和一些卡顿的地方） ——zc_cored------------------ 原始邮件 ------------------
发件人: "Dylech30th"<notifications@github.com>
发送时间: 2020年3月21日(星期六) 凌晨0:54
收件人: "Rinacm/Pixeval"<Pixeval@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Rinacm/Pixeval] 设置中的起始页设置和按收藏数排序似乎是无效的 (#46)




 
起始页仅仅对于关键字搜索有效
 收藏数排序仅仅对于日推和关键字搜索有效，其余的全部按照日期排序
 
&mdash;

**Comment by Rinacm** [comment]
什么ID咋办，如果你说的是用户收藏和用户作品的话，是一次性全部显示出来的，gif播放已经有了，卡顿是无法避免的，投稿这个东西我都不知道api，因为我从来没上传过作品

**Comment by naSgnahZ** [comment]
> 起始页仅仅对于关键字搜索有效
> 收藏数排序仅仅对于日推和关键字搜索有效，其余的全部按照日期排序

大佬,如果你说的'关键字搜索'指的是位于主页的那个搜索功能.  对于搜索起始页的设置,我输入从1~100的任何一个数字,所得到的搜索结果永远是相同的一页或几页. 且收藏数排序功能的开启与否,也不影响搜索结果的收藏数递减排序.   QAQ

**Comment by zccored** [comment]
我这边连不上去了，显示的是：“抱歉，Pixeval无法根据当前的设置找到任何作品，或许是您的页码设置过大/关键字...”
但我设置的作品收藏数：0；搜索页数：1。并且以前能查看的。
![image](https://user-images.githubusercontent.com/59573461/77219565-04407b80-6b72-11ea-8381-af605328288d.png)

**Comment by zccored** [comment]
使用版本是1.6.2....是最新版出bug了吗。。。

**Comment by Rinacm** [comment]
已修复并发布更新

**Comment by naSgnahZ** [comment]
> 已修复并发布更新

awesome
