### ISSUE TITLE
应用内下载的图片分辨率太低

### ISSUE THREAD

**Issue by xushet** [Rinacm/Pixeval#47]
![美图看看拼图_2020323113738](https://user-images.githubusercontent.com/34502902/77278633-d3d81900-6cfa-11ea-9bf4-233c1b571318.jpg)
与浏览器保存的差别好大

**Comment by Rinacm** [comment]
这个图片是在哪个栏里下载的，搜索还是用户收藏还是用户上传还是别的

**Comment by xushet** [comment]
> 这个图片是在那个栏里下载的，搜索还是用户收藏还是用户上传还是别的

在用户收藏下载的

**Comment by Rinacm** [comment]
能给出复现步骤吗？我这里下载的对比后都没有问题
![image](https://user-images.githubusercontent.com/31894334/77850690-c9d87d80-7206-11ea-8dab-cfbc1c17b05c.png)

**Comment by xushet** [comment]
> 能指定复现步骤吗？我这里下载的对比后都没有问题
> ![图片](https://user-images.githubusercontent.com/31894334/77850690-c9d87d80-7206-11ea-8dab-cfbc1c17b05c.png)

更新1.7.1之后没有问题了，
