### ISSUE TITLE
可以登录，但是登录进去图片加载不出来

### ISSUE THREAD

**Issue by CaoTY1995** [Rinacm/Pixeval#48]
设置如果不启用直连，就会显示“无法根据设置找到相应的图片”；启用直连，只会有图片的框框，而加载不出图片。

**Comment by Rinacm** [comment]
你去ping i.pximg.net试试，看看能不能ping通，如果能ping通那就是个人网络波动问题

**Comment by CaoTY1995** [comment]
> 你去ping i.pximg.net试试，看看能不能ping通，如果能ping通那就是个人网络波动问题

能ping动，但是就是没有图片，只能挂梯子过

**Comment by CaoTY1995** [comment]
> 你去ping i.pximg.net试试，看看能不能ping通，如果能ping通那就是个人网络波动问题

搞定了，之前改了hosts直翻的，现在失效了，把hosts改回来了就好了
