### ISSUE TITLE
图片排版可以增加瀑布流显示方式吗

### ISSUE THREAD

**Issue by xushet** [Rinacm/Pixeval#49]

**Comment by Rinacm** [comment]
之前有考虑过，但是瀑布流显示会增大虚拟化的压力，甚至没办法虚拟化

**Comment by Rinacm** [comment]
因为Pixeval最多的时候要显示4000张图甚至更多，所以瀑布流视图可能会导致内存占用暴增，当然也有解决办法，不过要重构很大一部分代码，等到我把手头的事都做完了会考虑一下

**Comment by Rinacm** [comment]
刚刚发现一个问题，瀑布流视图会导致图片排列取决于图片的长宽比，因此使用瀑布流排序就无法再使用排序功能了，因此在有解决办法以前暂时不考虑瀑布视图的问题

**Comment by xushet** [comment]
> 刚刚发现一个问题，瀑布流视图会导致图片排列取决于图片的长宽比，因此使用瀑布流排序就无法再使用排序功能了，因此在有解决办法以前暂时不考虑瀑布视图的问题

那就再等等吧😂
