### ISSUE TITLE
界面内容显示不全，做一下适配？？？

### ISSUE THREAD

**Issue by DANYI-CN** [Rinacm/Pixeval#51]
浏览了一下Issues中的相似建议，确实加了几个滚动条（最开始我下载的版本连侧边栏的滚动条都没有。。。），但是不是考虑一下不使用强制分辨率而根据不同的设备自动适配呢，这样似乎更加有效（当然好像这样修改工作量比较大，但只加几个滚动条似乎有些治标不治本）。

另外，每次登录时Pixiv事务局都会发邮件来说您有新的登录活动，UWP似乎不存在这个问题，使用cookies或者用些缓存？？？

![FeedBack](https://user-images.githubusercontent.com/42197263/78310295-0fd36f80-7580-11ea-9865-df84fee2efd1.png)

**Comment by Rinacm** [comment]
最新版本已修复

**Comment by DANYI-CN** [comment]
嗯，好的

**Comment by Rinacm** [comment]
另外关于异地登录的问题，我直连的时候是直接走的ip，而且credential使用的是OAuth而非cookie，Pixiv的Access Token时效只有1h，也就是每过1h就需要刷新一次，所以这个问题我不太能解决，因为我周围调查过一些用户，这个问题有的人经常遇到，有的人遇不到，不过可以肯定的是我这边不挂梯子一直走直连的话是不会提示的

**Comment by Rinacm** [comment]
然后图集只能查看第一张的问题希望可以阐述一下复现步骤，因为这个BUG我很早以前就针对修复了，用了这么久我都没有再遇到

**Comment by DANYI-CN** [comment]
嗯，更新之后长按就可以查看多张了（但没更新前我也试过长按，当时是没反应的。。emmm不明原因，也许是个bug，但很遗憾我无法帮你复现）。但是所说的一小时刷新一次。。。。我一直走的直连。。不管我过多久、多少次重新打开软件(就算是关掉后立即重开)，这封邮件从不爽约。。。。提供一下邮件的截屏吧，希望有所帮助
![无标题](https://user-images.githubusercontent.com/42197263/78341238-efc89e00-75c9-11ea-802c-5b532b345f3a.png)

**Comment by DANYI-CN** [comment]
另外，新版本里面图片排版都变成了单排横向滚动，是刻意为之？？？感觉回到了Win8时代😂

**Comment by Rinacm** [comment]
不是，你去更新一下，你现在用的那个版本有超级大的bug，可能导致CPU飙到20%，然后滚动条和ui也会错位

**Comment by Rinacm** [comment]
我已经在1.7.5更新了，你重启一下就能看到更新提示

**Comment by DANYI-CN** [comment]
哇塞，听起来超吓人，赶紧更新
![无标题](https://user-images.githubusercontent.com/42197263/78342730-4e8f1700-75cc-11ea-86d3-9612858938ba.png)

**Comment by Rinacm** [comment]
然后强制分辨率匹配是做不到的...因为我本身是做了分辨率下限的，就是1600*900，然后左侧导航栏的内容为了更加美观一点所以设计的比较大，也就固定了侧边栏的高度下限，这导致了只能使用滚动条而不能使用分辨率适配

**Comment by DANYI-CN** [comment]
嗯，了解，下次用我家台式，就是被看到了可能会被男女混合双打😂😂😂【手动滑稽】
