### ISSUE TITLE
一些图片搜索界面的控制功能

### ISSUE THREAD

**Issue by NanamiArihara** [Rinacm/Pixeval#53]
某些 Vim 语法（陆续还会接着点菜）
直接在搜索界面键入/搜索关键字

二次搜索并过滤，类似 MC 中 JEI/NEI 双击搜索框高亮搜索物品的操作
其他图片亮度调小

左下角显示一个信息框展示正在输入的命令（或许可以把进度之类的东西一块放过来）

**Comment by TheRealKamisama** [comment]
好！加！快！写！sUbsCRiBe tO tHiS tHrEaD

**Comment by Rinacm** [comment]
> 好！加！快！写！sUbsCRiBe tO tHiS tHrEaD

女子！女少！又寸！

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/commit/8c547014354a396af2db88f0973877cbd9c064eb

**Comment by NanamiArihara** [comment]
NTSB 你可以直接在 Commit 里面控制 Issues
只要写一行 Close #xx, Closed #xx, Fixed #xx 之类的，GitHub 就会自动给你关掉某 Issue 并添加 Commit 说明进去
