### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Csy2202** [Rinacm/Pixeval#56]
为什么软件图片加载很慢，打开了好久还没有加载。

**Comment by Csy2202** [comment]
![image](https://user-images.githubusercontent.com/63043903/81384195-e049f100-9143-11ea-8a1e-d0e56281e565.png)就像这样

**Comment by Rinacm** [comment]
图片加载是直接和你的网络相关联的，这种问题是个人网络的原因，我解决不了..

**Comment by Csy2202** [comment]
好的，谢谢啦



在 2020-05-08 16:02:02，"Dylech30th" <notifications@github.com> 写道：

图片加载是直接和你的网络相关联的，这种问题是个人网络的原因，我解决不了..
