### ISSUE TITLE
打开程序提示尚未安装根证书.md

### ISSUE THREAD

**Issue by AlanABCDE** [Rinacm/Pixeval#57]
![img](https://github.com/AlanABCDE/1551/blob/master/%E9%94%99%E8%AF%AF.png)
打开程序提示尚未安装根证书
如图然后点了是也没变化

**Comment by Rinacm** [comment]
没反应就是提示安装上去了呀...然后软件就会正常打开了

**Comment by AlanABCDE** [comment]
可是没打开啊

**Comment by AlanABCDE** [comment]
点是以后看任务管理器确实有Pixeval这个程序但是过了几秒就没了。再打开Pixeval.exe还是提示没安装证书

**Comment by Rinacm** [comment]
那你可能是没装vc++ redistributable，检查一下控制面板，看看自己有没有安装Visual C++ Redistributable 2015-2019,然后把%localappdata%/pixeval/crash-reports文件夹打包发出来

**Comment by Rinacm** [comment]
![image](https://user-images.githubusercontent.com/31894334/81543914-556a3000-93a9-11ea-9e6c-7ae93eafa4ac.png)
如图，一定要是x64版本的

**Comment by AlanABCDE** [comment]
[crash-reports.zip](https://github.com/Rinacm/Pixeval/files/4608808/crash-reports.zip)
x64 x86 都安装了
![捕获](https://user-images.githubusercontent.com/65140019/81547855-02937700-93af-11ea-907a-a3f9c546ef92.PNG)
这样的

**Comment by Rinacm** [comment]
好像是证书安装时候的问题，我待会去修一下

**Comment by AlanABCDE** [comment]
好，麻烦了

**Comment by Rinacm** [comment]
由于这个问题有点奇怪，所以我去[stackoverflow](https://stackoverflow.com/questions/61727585/net-core-throws-windowscryptographicexception-access-is-denied-on-x509store-ad/61728525#61728525)了一下,
![W0`Z9 7E7~G28KY)K{V$ZT2](https://user-images.githubusercontent.com/31894334/81567137-76914780-93ce-11ea-9311-a1b3563c31a7.png)
请在组策略管理器里查看下有关这一项的设置

**Comment by AlanABCDE** [comment]
我的家庭版没有gpedit.msc 按照网上的教程也添加不上..

**Comment by AlanABCDE** [comment]
![捕获1](https://user-images.githubusercontent.com/65140019/81645027-696e6a00-945b-11ea-86b0-993910d65d30.PNG)
然后点哪里我不会了

**Comment by Rinacm** [comment]
其实我今天搞了半天的注册表...我以为你没法打开GPO所以就把注册表给你找到了....结果你打开了

**Comment by Rinacm** [comment]
打开GPO以后选择计算机配置 | Windows设置 | 安全设置 | 公钥策略 | 证书路径验证设置，打开之后应该如图所示(我的系统是英文，你对照着来)

![M55Y)TPI8DLBRJ9{7GN4W~9](https://user-images.githubusercontent.com/31894334/81647101-0bdc1c80-945f-11ea-959b-f68f5983766b.png)

![NFNMI986%{($@$K 4U8GI80](https://user-images.githubusercontent.com/31894334/81647177-2910eb00-945f-11ea-85e4-e334252c190d.png)
在Define these policy settings一栏中把两个选项全部勾选，然后点击确定即可

**Comment by AlanABCDE** [comment]
这个方式试了可还是不行....

**Comment by Rinacm** [comment]
确定按照上面说的修改了？这次打开pixeval的时候有没有弹出一个类似安全警告的提示窗口，类似这种：
![image](https://user-images.githubusercontent.com/31894334/81668141-c9bed500-9476-11ea-8c5e-8fda9aad4e20.png)
再让我看看crash reports文件夹里面的最后一个文件

**Comment by Rinacm** [comment]
另外，你把你设置上面我发的那个东西的截图也发出来我看看有哪里做得不对

**Comment by AlanABCDE** [comment]
好的，我回家就给你发，我每次打开pixeval都弹出尚未安装根目录的窗口，这次修改完上面那个窗口没出过，弹出的还是未安装根目录的窗口

**Comment by AlanABCDE** [comment]
[05-12-2020 17-19-54.txt](https://github.com/Rinacm/Pixeval/files/4615346/05-12-2020.17-19-54.txt)
![捕获](https://user-images.githubusercontent.com/65140019/81685896-d4836500-948a-11ea-90b4-678f7f6b26ae.PNG)

**Comment by Rinacm** [comment]
![image](https://user-images.githubusercontent.com/31894334/81687270-8884f000-948b-11ea-9a77-d284509b062e.png)
受信任的发布者里面这么设置

**Comment by AlanABCDE** [comment]
![L_A~3VMASB(80KVICV8P @G](https://user-images.githubusercontent.com/65140019/81693404-6b9feb00-9492-11ea-8243-2d6f52f7bd28.png)
还是不行

**Comment by Rinacm** [comment]
...没辙了，我明天看看注册表，还是不行的话，那我就真的除了告诉你重装系统以外没别的招了

**Comment by AlanABCDE** [comment]
那行吧，没更新之前还是能用的，要不我还是用旧版吧

**Comment by Rinacm** [comment]
也说不定，明天我去看看注册表
