### ISSUE TITLE
个人修改意见

### ISSUE THREAD

**Issue by SuXi210** [Rinacm/Pixeval#58]
鼠标移动到图片上的模糊效果会把视线吸引过去，以至于我在下滑的时候都是把鼠标指针放在旁边
建议去掉模糊，只把图片稍微放大一下，同时鼠标移动到图片上后显示图片分辨率
（⌒▽⌒）

**Comment by SuXi210** [comment]
不好意思，第一次在GitHub上提出自己的意见，不知道怎么删除这个BUG标签

**Comment by Rinacm** [comment]
没事，我待会看看

**Comment by SuXi210** [comment]
谢谢

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/releases/tag/2.1.1
