### ISSUE TITLE
为什么我单击预览图打不开原图

### ISSUE THREAD

**Issue by Jack6811** [Rinacm/Pixeval#60]
就是我在升级到最新版2.1.2中，我单击以后打不开大图了，只有动画效果

**Comment by Rinacm** [comment]
动画效果？具体怎么个打不开法

**Comment by Jack6811** [comment]
单击没有任何反应，只有那个点击的阴影

**Comment by MiaoQiQwQ** [comment]
同问

**Comment by MiaoQiQwQ** [comment]
> 动画效果？具体怎么个打不开法

就是每日推荐和榜单点进去过后只能看到缩略图，点击缩略图无法弹出画作大图

**Comment by MiaoQiQwQ** [comment]
就是在每日推荐或者作品榜单中只能看到缩略图，点缩略图打不开画作

**Comment by Rinacm** [comment]
crash reports文件夹里能找到崩溃报告吗？

**Comment by Rinacm** [comment]
win+r打开%localappdata%/pixeval文件夹，crash reports内容打包发上来

**Comment by Rinacm** [comment]
新版本已修复
