### ISSUE TITLE
登录时遇到一个问题导致无法登录

### ISSUE THREAD

**Issue by assdrf** [Rinacm/Pixeval#61]
在登陆时已经输完了账号和密码，点击登录时仍出现”用户名或密码不能为空“字样。
输入密码时，密码第一个字母输入时无反应，会从第二位开始输入。
输入时密码为明文，且无法直接使用删除键删除。
![批注 2020-05-24 092044](https://user-images.githubusercontent.com/65837247/82743610-479cad80-9da0-11ea-8a13-e02eedc0a1ae.png)

**Comment by Rinacm** [comment]
输入的时候不要开输入法..这个是WPF框架的问题，这个框架本身就不支持中文输入法

**Comment by assdrf** [comment]
> 输入的时候不要开输入法..这个是WPF框架的问题，这个框架本身就不支持中文输入法

好的，谢谢
