### ISSUE TITLE
用户动态不能右键下载

### ISSUE THREAD

**Issue by SuXi210** [Rinacm/Pixeval#62]
用户动态里的缩略图不能右键下载，需要点开后再下载

**Comment by SuXi210** [comment]
如果能支持一下夜间模式就好了，晚上的时候打开有点伤眼睛

**Comment by Rinacm** [comment]
夜间模式暂时没打算写，以后可能有打算
动态哪里的话的确是不支持右键下载的...因为感觉有点不搭

**Comment by SuXi210** [comment]
还有一个问题就是，在用户新作里好像会一直加载已关注用户的所有作品，哪怕不往下滑动，都能看见滑条一直在变短

**Comment by Rinacm** [comment]
这个是一次性加载完的，但是因为用了虚拟化技术所以加载完的东西并不是全部在内存里，可以放心用
