### ISSUE TITLE
通常每个套接字地址(协议/网络地址/端口)只允许使用一次

### ISSUE THREAD

**Issue by qbs233** [Rinacm/Pixeval#63]
![image](http://bm233.xyz:666/?/images/2020/05/27/nd8CAThHp1/TIM%E6%88%AA%E5%9B%BE20200527200341.bmp)

**Comment by Rinacm** [comment]
因为我本地代理服务器默认端口是1234和4321..被占用了就会出现这个问题，我明天修一下放新版本

**Comment by lmc1998913** [comment]
感谢！

**Comment by Rinacm** [comment]
新版本已修复 https://github.com/Rinacm/Pixeval/releases/tag/2.1.4
