### ISSUE TITLE
【Win10】经常在点开图片页面时卡死，且无法通过点击任务栏图标将程序切至前台。

### ISSUE THREAD

**Issue by Himmelt** [Rinacm/Pixeval#64]
![image](https://user-images.githubusercontent.com/12007165/83146634-313c7c00-a129-11ea-815e-f65c1b499772.png)

**Comment by Rinacm** [comment]
明天我看下

**Comment by qbs233** [comment]
现在这个版本噎死

**Comment by Rinacm** [comment]
bug已经修复了，但是我要过段时间才能发布，这段时间作业太多，没时间..

**Comment by Rinacm** [comment]
新版本应该已经修复，再次出现请开新issue
