### ISSUE TITLE
233

### ISSUE THREAD

**Issue by Melon233** [Rinacm/Pixeval#67]
你好，我这边的情况是进入程序后无法显示内容
![屏幕截图(5)](https://user-images.githubusercontent.com/66622831/84030563-dcb9bc00-a9c6-11ea-80a8-7df0cac27ee8.png)
![屏幕截图(6)](https://user-images.githubusercontent.com/66622831/84030567-ddeae900-a9c6-11ea-8eae-7a91cdd7c1cf.png)
![屏幕截图(7)](https://user-images.githubusercontent.com/66622831/84030569-de837f80-a9c6-11ea-8083-7aefc32c44fe.png)
![屏幕截图(8)](https://user-images.githubusercontent.com/66622831/84030574-dfb4ac80-a9c6-11ea-83e8-afc4de993a42.png)
![屏幕截图(9)](https://user-images.githubusercontent.com/66622831/84030576-e0e5d980-a9c6-11ea-8553-6530a357e21a.png)

**Comment by Rinacm** [comment]
在设置里确保打开了直连选项，如果不打开直连选项默认需要挂代理访问

**Comment by Melon233** [comment]
好了，谢谢~~
