### ISSUE TITLE
是否考虑去掉CefSharp减少打包体积呢?

### ISSUE THREAD

**Issue by dxafn** [Rinacm/Pixeval#68]
我粗略看了部分代码，有部分功能使用WEB接口；如果考虑半自动化，即登录时手动输入可选的PHPSESSID，这样就可以不用依赖 CefSharp 和代理服务器（及自签名证书）了

**Comment by Rinacm** [comment]
我也有这么想过，但是感觉大部分用户根本不会这么干.....
