### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by lushuyu** [Rinacm/Pixeval#7]
I am new in C#.
I don't know why it fails.
![TIM截图20191222125030](https://user-images.githubusercontent.com/27007632/71317309-f5d2bd00-24b9-11ea-84fd-bee3cb5dc0e7.png)

**Comment by lushuyu** [comment]
但是我删去了所有有关“LOG”的代码后，构建成功了...哪儿出了问题？

**Comment by Rinacm** [comment]
it's a little bug might cause of git's commit action, I've already fix it, you can re-clone it now

**Comment by lushuyu** [comment]
> it's a little bug might cause of git's commit action, I've already fix it, you can re-clone it now

OK,I close this.

**Comment by Rinacm** [comment]
> 但是我删去了所有有关“LOG”的代码后，构建成功了...哪儿出了问题？

seems the "Pixeval.Objects.Exceptions.Log" folder been excluded, I might need to check the gitignore file

**Comment by lushuyu** [comment]
> it's a little bug might cause of git's commit action, I've already fix it, you can re-clone it now

reference it to b6eec8a?
