### ISSUE TITLE
pixeval2.2.3打开运行一段时间后程序卡死

### ISSUE THREAD

**Issue by ffj1239916965** [Rinacm/Pixeval#75]
打开pixeval2.2.3使用大概1-3分钟，界面就会锁死，点击界面所有地方都没反应。只能用任务管理器结束进程才能再次打开

**Comment by Jack6811** [comment]
考虑考虑旧版本吧，这个版本会有一些奇奇怪怪的Bug

**Comment by Rinacm** [comment]
先用着旧版本，我最近忙没时间修，忙完再说

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/releases/latest
fixed
