### ISSUE TITLE
我的问题

### ISSUE THREAD

**Issue by WSNLZDY** [Rinacm/Pixeval#84]
为什么我昨天可以打开但是今天就打不开了，我把pixeval，重下了一遍，还是不行，不知道是怎么回事。

**Comment by Jack6811** [comment]
试着删除%AppData%\..\Local\pixeval目录。实在不行考虑考虑自己编译源代码吧。

**Comment by WSNLZDY** [comment]
我还是不懂

**Comment by Rinacm** [comment]
> 我还是不懂

这几天家里出了非常大的事情....作者我已经把bug修复了，但是苦于精神和物质上的双重压力没精力发布，过段时间我会尽快发布的....请耐心一点

**Comment by Rinacm** [comment]
https://github.com/Rinacm/Pixeval/releases/latest
fixed
