### ISSUE TITLE
作者停更了？

### ISSUE THREAD

**Issue by Jack6811** [Rinacm/Pixeval#85]
作者已经快3个月没有进行更新了，小伙伴给提交的代码作者也没有进行构建，难道弃坑了？有没有什么windows端的代替品啊？

**Comment by Jack6811** [comment]
再有就是那个防多开的部分，在未响应被任务管理器强制ban了主进程后会出现其服务无法自动关闭的问题。会导致软件无法重启，有可以维护的大佬看看吧。

**Comment by Rinacm** [comment]
没有弃坑，我没有更新的原因是家里出了大事，理解一下
代码已经全部写好了，等到这段时间过去就会更新

**Comment by Jack6811** [comment]
好的，感谢作者。那您就先处理家里的事情吧。
