### ISSUE TITLE
功能建议III

### ISSUE THREAD

**Issue by czh098tom** [Rinacm/Pixeval#9]
- [ ] 收藏和关注添加切换private功能
- [ ] 图片组中下载图片时文件名增加序号，否则后下载的图片会自动覆盖先下载的图片

**Comment by Rinacm** [comment]
> * [ ]  收藏和关注添加切换private功能
> * [ ]  图片组中下载图片时文件名增加序号，否则后下载的图片会自动覆盖先下载的图片

添加序号是有的，切换private会列入日程
