### ISSUE TITLE
他说我缺少.NET

### ISSUE THREAD

**Issue by NotFoundNEKKO** [Rinacm/Pixeval#92]
[它提示说我缺少.net，我已经点了是，而且下载安装了，它还是提示，我应该怎么办？]
![QQ截图20200814223213](https://user-images.githubusercontent.com/47251157/90260430-0dfab080-de7e-11ea-8590-82fa6d2580fa.png)

**Comment by Summpot** [comment]
这玩意儿应该只是个壳，没有做具体的功能，你打得开powershell吗

**Comment by NotFoundNEKKO** [comment]
可以的

**Comment by Summpot** [comment]
```powershell
(iwr https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1 -OutFile ./dotnet-install.ps1);./temp.ps1 -Runtime "windowsdesktop";ri ./dotnet-install.ps1;
```
找个powershell然后复制进去

**Comment by NotFoundNEKKO** [comment]
![image](https://user-images.githubusercontent.com/47251157/90310192-dba28f00-df21-11ea-8beb-b07709ad9af3.png)

**Comment by Summpot** [comment]
艹，之前我忘改了，现在改了，你再试一次把，还是在上面

**Comment by NotFoundNEKKO** [comment]
![image](https://user-images.githubusercontent.com/47251157/90310214-2ae8bf80-df22-11ea-9f0e-82494a41113c.png)

**Comment by Summpot** [comment]
Set-ExecutionPolicy RemoteSigned

**Comment by Summpot** [comment]
先执行这个

**Comment by NotFoundNEKKO** [comment]
![image](https://user-images.githubusercontent.com/47251157/90310344-54561b00-df23-11ea-825e-705f1ab91f25.png)

**Comment by NotFoundNEKKO** [comment]
![image](https://user-images.githubusercontent.com/47251157/90310435-d2b2bd00-df23-11ea-80be-7f18af75f044.png)

**Comment by Summpot** [comment]
艹

**Comment by Summpot** [comment]
https://download.visualstudio.microsoft.com/download/pr/5e4695fb-da51-4fa8-a090-07a64480888c/65aa842670d2280b5d05b8a070a9f495/windowsdesktop-runtime-3.1.7-win-x64.exe

**Comment by NotFoundNEKKO** [comment]
![image](https://user-images.githubusercontent.com/47251157/90310657-18708500-df26-11ea-9b81-4df2aae8777c.png)

**Comment by NotFoundNEKKO** [comment]
好的可以了谢谢大佬
