### ISSUE TITLE
求助下大佬，打不开软件，双击应用什么反应都没有

### ISSUE THREAD

**Issue by gka123** [Rinacm/Pixeval#99]
以前能打开，后来重装系统后就打不开了，.NET Core 3.1 Runtime跟Visual C++ Redistributable 2015-2019都安装了，我的是win7，在想是不是没安装说明里的https://www.microsoft.com/en-us/download/details.aspx?id=26764这个补丁，不过这补丁进去后不能下载了。。。该怎么办.......

**Comment by Rinacm** [comment]
win7的KB2533623补丁，就是这个，你去找找下载一下，不知道为啥ms把这个补丁给撤了，再不行的话以后有可能撤掉对win7的支持

**Comment by gka123** [comment]
> win7的KB2533623补丁，就是这个，你去找找下载一下，不知道为啥ms把这个补丁给撤了，再不行的话以后有可能撤掉对win7的支持

非常感谢，搜了这个补丁安装后终于可以正常打开了。谢谢大佬，辛苦了
